/**
 * @fileoverview Types for intelligent concept extraction and highlighting.
 * 
 * The concept system enables automatic detection and highlighting of key concepts
 * within question text. Concepts are extracted via LLM, categorized for color-coded
 * display, and can be expanded with on-demand explanations in Gwern-style popups.
 * 
 * @example
 * ```typescript
 * // Example of extracted concepts from a question
 * const concepts: ExtractedConcept[] = [
 *   {
 *     id: 'c_1706745600000_abc123',
 *     text: 'evolutionary',
 *     normalizedName: 'evolution',
 *     category: 'science',
 *     startIndex: 24,
 *     endIndex: 36
 *   }
 * ]
 * ```
 */

/**
 * Categories for concept classification.
 * 
 * Each category maps to a distinct highlight color in the UI.
 * Categories are intentionally broad to maintain visual consistency
 * while providing semantic meaning.
 */
export type ConceptCategory =
  | 'science'      // biology, physics, chemistry, mathematics
  | 'philosophy'   // cognition, consciousness, epistemology, metaphysics
  | 'psychology'   // behavior, emotion, mental processes
  | 'technology'   // computing, AI, engineering, systems
  | 'abstract'     // general concepts, relationships, meta-topics

/**
 * Represents a concept extracted from question text.
 * 
 * Each concept contains positional information for accurate highlighting
 * and semantic information for categorization and explanation.
 */
export interface ExtractedConcept {
  /**
   * Unique identifier for this concept instance.
   * Format: `c_${timestamp}_${randomString}`
   */
  id: string

  /**
   * The original text span as it appears in the source.
   * Example: "evolutionary" from "evolutionary byproduct"
   */
  text: string

  /**
   * Canonical/normalized name for the concept.
   * Used for caching explanations and grouping related mentions.
   * Example: "evolution" for text "evolutionary"
   */
  normalizedName: string

  /**
   * Semantic category for color-coded highlighting.
   */
  category: ConceptCategory

  /**
   * Zero-based start index of the concept in the source text.
   */
  startIndex: number

  /**
   * Zero-based end index (exclusive) of the concept in the source text.
   */
  endIndex: number
}

/**
 * Explanation content for a concept, generated by LLM.
 * 
 * Contains both a standalone summary and context-aware explanation
 * that relates the concept to the user's specific question.
 */
export interface ConceptExplanation {
  /**
   * ID of the concept this explanation is for.
   */
  conceptId: string

  /**
   * Canonical name of the concept.
   */
  normalizedName: string

  /**
   * Brief standalone explanation of the concept.
   * Should be 2-3 sentences, accessible to a general audience.
   */
  summary: string

  /**
   * Contextual explanation of how this concept relates to the user's question.
   * Tailored to the specific question being explored.
   */
  context: string

  /**
   * List of related concept names for potential sub-tree expansion.
   * These can become new branches in the question exploration tree.
   */
  relatedConcepts: string[]
}

/**
 * Response from the concept extraction API.
 */
export interface ConceptExtractionResponse {
  success: boolean
  data: {
    concepts: ExtractedConcept[]
    /** The original text that was analyzed */
    sourceText: string
  }
}

/**
 * Response from the concept explanation API.
 */
export interface ConceptExplanationResponse {
  success: boolean
  data: ConceptExplanation
}

/**
 * Generates a unique identifier for a concept.
 * 
 * Format: `c_${timestamp}_${random}`
 * - Prefix 'c_' for easy identification (vs 'q_' for questions)
 * - Timestamp for rough ordering/debugging
 * - Random suffix for uniqueness
 * 
 * @returns A unique string ID
 * 
 * @example
 * ```typescript
 * const id = generateConceptId() // "c_1706745600000_abc123"
 * ```
 */
export const generateConceptId = (): string => {
  return `c_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`
}

/**
 * Maps a category string to its display color CSS variable name.
 * 
 * @param category - The concept category
 * @returns CSS custom property name for the category color
 * 
 * @example
 * ```typescript
 * const colorVar = getCategoryColorVar('science') // '--concept-science'
 * ```
 */
export const getCategoryColorVar = (category: ConceptCategory): string => {
  return `--concept-${category}`
}

/**
 * Human-readable labels for concept categories.
 */
export const categoryLabels: Record<ConceptCategory, string> = {
  science: 'Science',
  philosophy: 'Philosophy',
  psychology: 'Psychology',
  technology: 'Technology',
  abstract: 'General Concept',
}

/**
 * Sorts concepts by their start index for proper rendering order.
 * 
 * @param concepts - Array of extracted concepts
 * @returns New array sorted by startIndex ascending
 */
export const sortConceptsByPosition = (
  concepts: ExtractedConcept[]
): ExtractedConcept[] => {
  return [...concepts].sort((a, b) => a.startIndex - b.startIndex)
}

/**
 * Validates that concepts don't overlap in the source text.
 * Overlapping concepts would cause rendering issues.
 * 
 * @param concepts - Array of extracted concepts (should be sorted)
 * @returns True if no concepts overlap
 */
export const validateNoOverlap = (concepts: ExtractedConcept[]): boolean => {
  const sorted = sortConceptsByPosition(concepts)
  for (let i = 1; i < sorted.length; i++) {
    if (sorted[i].startIndex < sorted[i - 1].endIndex) {
      return false
    }
  }
  return true
}
